apiVersion: apps/v1
kind: Deployment
metadata:
 name: order
spec:
 replicas: 1
 selector:
   matchLabels:
     app: order
 template:
   metadata:
     labels:
       app: order
   spec:
     containers:
     - name: order
       image: xjxiao/orderapi
---
apiVersion: v1
kind: Service
metadata:
 name: order
 annotations:
   konghq.com/plugins: twelve-per-min
spec:
  type: NodePort
  selector:
    app: order
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32244